
version: '3.8'

services:
  server1:
    image: localhost/arbokcore:latest
    environment:
      - SERVER_ID=server1
    ports:
      - "9191:9191"
    expose:
      - "9191"
    volumes:
      - ./dockerdb:/app/dbs
    networks:
      - app-network

  server2:
    image: localhost/arbokcore:latest
    environment:
      - SERVER_ID=server2
    volumes:
      - ./dockerdb:/app/dbs
    ports:
      - "9192:9191"
    expose:
      - "9191"
    networks:
      - app-network

  arbokcli:
    entrypoint: ["echo", "not implemented"]
    networks:
      - app-network

  arbokworker:
    image: localhost/arbokworker:latest
    command: "supervise -name metadatas"
    args:
      BUILD_VERSION: ${BUILD_VERSION}
    volumes:
      - ./dockerdb:/app/dbs
    networks:
      - app-network


volumes:
  dockerdb:

networks:
  app-network:
    driver: bridge
