
version: '3.8'

services:
  server1:
    build: .
    environment:
      - SERVER_ID=server1
    ports:
      - "9191:9191"
    expose:
      - "9191"
    volumes:
      - ./dockerdb:/app
    networks:
      - app-network

  server2:
    build: .
    environment:
      - SERVER_ID=server2
    volumes:
      - ./dockerdb:/app
    ports:
      - "9192:9191"
    expose:
      - "9191"
    networks:
      - app-network

  arbokcli:
    build:
      context: .
      dockerfile: cli.Dockerfile
      args:
        BUILD_VERSION: ${BUILD_VERSION}
    volumes:
      - ./dockerdb:/app
    images: arbokcli
    networks:
      - app-network

volumes:
  dockerdb:

networks:
  app-network:
    driver: bridge
